---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
        exclude: src/domainManagementUI/src/assets/userguide/
      - id: check-merge-conflict
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
        exclude: src/secrets/privkey.pem
      - id: end-of-file-fixer
        exclude: files/(issue|motd)|src/domainManagementUI/src/assets/userguide/
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: src/domainManagementUI/src/assets/userguide/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
