version: "3.5"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cset-analytics-ui
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./src/CsetAnalytics:/app
    networks:
      - backend
networks:
  backend:
    name: cset_backend
